MODEL:
  model: 'PixArtMS_XL_2'
  STYLE_ENCODER_LAYERS: 3
  IN_CHANNELS: 4
  OUT_CHANNELS: 4
  NUM_RES_BLOCKS: 1
  NUM_HEADS: 4
  EMB_DIM: 512
  lewei_scale: 1.0
  fp32_attention: True
  grad_checkpointing: True
  pred_sigma: False
SOLVER:
  BASE_LR: 0.0001
  EPOCHS: 500
  WARMUP_ITERS: 3000
  TYPE: AdamW  # TODO, support optional optimizer
  GRAD_L2_CLIP: 5.0
TRAIN:
  TYPE: train
  IMS_PER_BATCH: 128
  SNAPSHOT_BEGIN: 0
  SNAPSHOT_ITERS: 10
  VALIDATE_BEGIN: 0
  VALIDATE_ITERS: 1
  SEED: 1001
  IMG_H: 64
  IMG_W: 64
TEST:
  TYPE: test
  IMS_PER_BATCH: 64
  IMG_H: 64
  IMG_W: 64
DATA_LOADER:
  NUM_THREADS: 8
  IMAGE_PATH: ./data/IAM64-new
  STYLE_PATH: ./data/IAM64-new
  LAPLACE_PATH: ./data/IAM64_laplace